project:
  type: website
  output-dir: _site

execute:
  enabled: false

website:
  title: "MEDAS Financial Reporting"
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/surybang/MEDAS-Financial-Reporting
  navbar:
    right:
      - icon: github
        href: https://github.com/surybang/MEDAS-Financial-Reporting
        aria-label: GitHub
  sidebar:
    style: docked
    search: true
    contents:
      - text: "Accueil"
        href: index.qmd
      - section: "Un long fleuve pas si tranquille"
        contents:
          - pages/01-introduction.qmd
          - pages/02-situation-de-depart.qmd
          - pages/03-situation-cible.qmd
          - pages/04-planification.qmd
          - pages/05-le-code.qmd
          - pages/06-tests.qmd
          - pages/07-integration-continue.qmd
          - pages/08-streamlit.qmd
          - pages/09-docker.qmd
          - pages/10-argocd.qmd

format:
  html:
    code-fold: true
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    anchor-sections: true
    smooth-scroll: true

license: "CC BY-NC"